version: 2
jobs:
  build:
    docker:
      - image: ubuntu:disco
    steps:
      - checkout
      - run: apt-get update && apt-get install -y qt5-default libgphoto2-dev
      - run: qmake
      - run: make
